//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Tickets_Sp_Tec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIAL_REPORTES
    {
        public int ID_HISTORIAL { get; set; }
        public int ID_REPORTE { get; set; }
        public int ID_TECNICO { get; set; }
        public Nullable<System.DateTime> FECHA_SOLUCION { get; set; }
        public string COMENTARIOS { get; set; }
    
        public virtual REPORTES REPORTES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
