//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Tickets_Sp_Tec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPORTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public REPORTES()
        {
            this.HISTORIAL_REPORTES = new HashSet<HISTORIAL_REPORTES>();
        }
    
        public int ID_REPORTE { get; set; }
        public Nullable<System.DateTime> FECHA_REPORTE { get; set; }
        public string DESCRIPCION { get; set; }
        public string PRIORIDAD { get; set; }
        public string ESTADO { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_TECNICO { get; set; }
        public Nullable<System.DateTime> FECHA_SOLUCION { get; set; }
        public string OBSERVACIONES { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORIAL_REPORTES> HISTORIAL_REPORTES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
        public virtual USUARIOS USUARIOS1 { get; set; }
    }
}
